### ISSUE TITLE
SSL Error when trying to connect

### ISSUE THREAD

**Issue by daniwaxman** [pjmuller/zendesk-helpcenter-export#12]
I am trying to use this script but I am getting the following error when running:

C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect
returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)

**Comment by jennyb-ctw** [comment]
I'm having the same issue. Here's the response I get when I run the script as documented:

```
C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect
returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify fai
led (OpenSSL::SSL::SSLError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty
/request.rb:118:in `perform'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty
.rb:560:in `perform_request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty
.rb:486:in `get'
        from zendesk-helpcenter-export.rb:255:in `api'
        from zendesk-helpcenter-export.rb:279:in `categories'
        from zendesk-helpcenter-export.rb:76:in `to_html!'
        from zendesk-helpcenter-export.rb:329:in <main>
```

I'm entering all the ZD account params correctly. However, I'm at a loss as to what to do to fix this. I'm running Ruby 2.3.1 on Windows 7. Will see if I'll have more success with this with a fresh Ruby install on a Mac, but would love to get this sorted for Windows if at all possible. Thanks in advance for any insight you might be able to share! (And thanks for the script -- if I can get it working, it'll be a great backup solution for my team!)

**Update:** Further investigation on the Zendesk support community leads me to believe this error is probably caused by my account being configured with the SSO security option, rather than the default Zendesk security option. Since I'm unsure how safe it is to disable SSO, run the script, and re-enable SSO (without regenerating a new secret), I'll have to settle for making raw content backups using Zendesk's Python solution. Thanks anyway!!
