### ISSUE TITLE
Crashses after a page or two (every time)

### ISSUE THREAD

**Issue by theskuj** [pjmuller/zendesk-helpcenter-export#19]
theskuj@server:/mnt/raid$ ruby zendesk-helpcenter-export.rb -e *** -p '***' -d ***
TTI SUITE - GENERAL INFORMATION
  About TTI Worksheets
zendesk-helpcenter-export.rb:86:in `block (2 levels) in to_html!': undefined method `each' for nil:NilClass (NoMethodError)
        from zendesk-helpcenter-export.rb:82:in `each'
        from zendesk-helpcenter-export.rb:82:in `block in to_html!'
        from zendesk-helpcenter-export.rb:78:in `each'
        from zendesk-helpcenter-export.rb:78:in `to_html!'
        from zendesk-helpcenter-export.rb:329:in `<main>'

**Comment by jonnobright** [comment]
I have the same issue - about to begin investigation

**Comment by markhedberg** [comment]
Not really a "fix," but I was able to _avoid_ the error by changing some things around in our Zendesk help center:

* When the section's `Order articles by` value is set to `Alphabetically by title` I get the same errors that @theskuj mentioned.
* When I set the `Order articles by` value to `Manually` the script successfully downloads the contents of the section...
  * **HOWEVER** - It appears that it only downloads the first page (30 articles) of a multi-page section containing more than 30 articles...
