### ISSUE TITLE
`block (2 levels) in to_html!': undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tjhorwood** [pjmuller/zendesk-helpcenter-export#21]
@pjmuller I am getting this error about half way through the export process:
```
zendesk-helpcenter-export.rb:86:in `block (2 levels) in to_html!': undefined method `each' for nil:NilClass (NoMethodError)
	from zendesk-helpcenter-export.rb:82:in `each'
	from zendesk-helpcenter-export.rb:82:in `block in to_html!'
	from zendesk-helpcenter-export.rb:78:in `each'
	from zendesk-helpcenter-export.rb:78:in `to_html!'
	from zendesk-helpcenter-export.rb:329:in `<main>'
```

**Comment by tjhorwood** [comment]
Closing because this is a duplicate of Issue #19
